#Run docker-compose up --build
#Run sudo systemctl stop mongob or delete other mongod container/ previous api images if you face any error
version: "3"
services:
  quoraforcollege_api:
    container_name: quoraforcollege-api-container
    restart: always
    image: docker.io/siddhantkhisty/quora-for-college:latest
    env_file: .env
    ports:
      - "8080:8080"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
    networks:
      - node-webapp-network
  mongodb:
    container_name: mongodb
    image: mongo:4.4.6
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_STRING}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=admin
    networks:
      - node-webapp-network
networks:
  node-webapp-network:
    driver: bridge